name: daily-testing
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'
      - name: Run test
        run: |
          go test github.com/nmemoto/gh-trending/...